version: 2.1
jobs:

  install_dependencies:
    docker:
      - image: circleci/node:12
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: curl -o- -L https://yarnpkg.com/install.sh | bash
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  audit:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: yarn audit

  lint:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: yarn lint

  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: yarn build

  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: yarn test

workflows:
  build_and_test:
    jobs:
      - install_dependencies 
      - audit:
          requires:
            - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - build:
          requires:
            - install_dependencies
      - test:
          requires:
            - build
